# Generated by Django 5.2.4 on 2025-08-18 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_aula_material_extra_alter_instrutor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video_id',
            field=models.CharField(blank=True, help_text='Cole apenas o ID.', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Informe apenas o ID do youtube (11 caracteres)', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
    ]
