# Generated by Django 5.2.4 on 2025-09-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='material_pdf',
            field=models.FileField(blank=True, help_text='PDF do material de apoio do curso', null=True, upload_to='materiais/'),
        ),
    ]
