# Generated by Django 5.2.4 on 2025-09-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_material_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Certificado de conclusão de curso', null=True, upload_to='materiais/'),
        ),
    ]
