# Generated by Django 5.2.4 on 2025-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_certificado_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='certificado_pdf',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='codigo_certificado',
            field=models.UUIDField(blank=True, default=False, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
