# Generated by Django 5.2.4 on 2025-09-16 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_curso_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='codigo_certificado',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
