# Generated by Django 5.2.4 on 2025-09-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_inscricao_codigo_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='expira_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pago_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
