# Generated by Django 5.2.4 on 2025-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_inscricao_ativo_inscricao_expira_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_id', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
