# Generated by Django 5.2.4 on 2025-09-30 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_transacaoimportada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacaoimportada',
            old_name='txt_id',
            new_name='tx_id',
        ),
        migrations.AlterField(
            model_name='curso',
            name='material_pdf',
            field=models.FileField(blank=True, help_text='PDF de material de apoio do curso', null=True, upload_to='materiais/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='video_id',
            field=models.CharField(blank=True, help_text='Cole apenas o ID.', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Informe apenas o ID do YouTube (11 caracteres).', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
    ]
